1069 mv ext e endpoint
jonatasoli/fast-ecommerce-back pull request #1074
Opened 2023-07-21 16:12 UTC by Luiz-Lins

O objetivo deste commit é avaliar os erros de tests e lint em localbranch.

2023-07-21 18:25 UTC, jonatasoli commented on app/infra/config.py
acho que esse arquivo nao era pra estar aqui e nem estar vazio. se existir o config no diretório root entao só paagar esse.

2023-07-21 18:35 UTC, jonatasoli requested changes

2023-07-21 18:35 UTC, jonatasoli commented on app/infra/database.py
aqui também deveria ter algum conteúdo e está vazio

2023-07-21 18:35 UTC, jonatasoli commented on app/infra/endpoints/default.py
outro arquivo que está vazio mas, deveria ter conteúdo.

2023-07-21 18:35 UTC, jonatasoli commented on app/infra/endpoints/tests/test_mail.py
d apra dar uma olhada que o teste ta vazio?

2023-07-21 18:35 UTC, jonatasoli commented on app/infra/endpoints/tests/test_order.py
isso ta estranho esse retorno parece estar fora.

2023-07-21 18:35 UTC, jonatasoli commented on app/infra/endpoints/tests/test_users.py
sem dados também

2023-07-21 18:35 UTC, jonatasoli commented on erros.txt
pode remover

2023-07-22 15:21 UTC, Luiz-Lins commented on app/infra/config.py
Mas esse arquivo existia dentro de "ext".  Na raiz tem um config com o seguinte conteúdo:

"""
.config
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix='DYNACONF',
    settings_files=['settings.toml', '.secrets.toml'],
    environments=True,
)

# `envvar_prefix` = export envvars with `export DYNACONF_FOO=bar`.
# `settings_files` = Load this files in the order.

"""

e o arquivo app/infra/config.py tem o seguinte conteúdo:

"""
from pydantic import BaseSettings


class Settings(BaseSettings):
    app_name: str = 'FAST Ecommerce API'
    items_per_user: int = 50

    class Config:
        env_file = '.env'
""""


Não entendi a questão do arquivo vazio.

2023-07-24 14:05 UTC, jonatasoli commented
Está sem pasta static isso vai dar erro.

2023-08-14 08:44 UTC, jonatasoli requested changes

2023-08-14 08:44 UTC, jonatasoli commented on .idea/.gitignore
> +# Default ignored files
Não deveria vir esse arquivo tem que tirar da review.

2023-08-14 08:44 UTC, jonatasoli commented on .idea/fast-ecommerce-back.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Não deveria vir esse arquivo tem que tirar da review.

2023-08-14 08:44 UTC, jonatasoli commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
Não deveria vir esse arquivo tem que tirar da review.

2023-08-14 08:44 UTC, jonatasoli commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Não deveria vir esse arquivo tem que tirar da review.

2023-08-14 08:44 UTC, jonatasoli commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Não deveria vir esse arquivo tem que tirar da review.

2023-08-14 08:44 UTC, jonatasoli commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Não deveria vir esse arquivo tem que tirar da review.

2023-08-21 17:44 UTC, jonatasoli commented on app/infra/endpoints/default.py
havia alguns endpoints aqui no default 


```python
from fastapi import APIRouter

inventory = APIRouter(
    prefix='/inventory',
    tags=['inventory'],
)
reviews = APIRouter(
    prefix='/reviews',
    tags=['reviews'],
)

coupons = APIRouter(
    prefix='/coupons',
    tags=['coupons'],
)
reports = APIRouter(
    prefix='/reports',
    tags=['reports'],
)
campaing = APIRouter(
    prefix='/campaing',
    tags=['campaing'],
)

sales = APIRouter(
    prefix='/sales',
    tags=['sales'],
)
```

2023-08-21 17:47 UTC, jonatasoli requested changes

2023-08-21 17:47 UTC, jonatasoli commented on docker-compose.yml
praise

2023-08-21 17:49 UTC, jonatasoli commented on README.md
> +git clone https://github.com/jonatasoli/fast-ecommerce-back.git
praise

2023-08-24 20:36 UTC, closed without merging